a = 6
b = 9
print(a, "+", b, "=", a+b)
print(a, "-", b, "=", a-b)
print(a, "/", b, "=", a/b)
print(a, "*", b, "=", a*b)
print(a, "**", b, "=", a**b)
print(a, "%", b, "=", a%b)
print(a, "//", b, "=", a//b)
